[package]
name = "gestion-mdp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
aes-gcm = "0.10.3"
clap = { version = "4.0", features = ["derive"] }